# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'p1_ejemplo.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(386, 413)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 50, 55, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 90, 55, 16))
        self.label_2.setObjectName("label_2")
        self.txt_num1 = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_num1.setGeometry(QtCore.QRect(130, 50, 113, 22))
        self.txt_num1.setText("")
        self.txt_num1.setObjectName("txt_num1")
        self.txt_num2 = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_num2.setGeometry(QtCore.QRect(130, 90, 113, 22))
        self.txt_num2.setText("")
        self.txt_num2.setObjectName("txt_num2")
        self.btn_sumar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sumar.setGeometry(QtCore.QRect(120, 140, 93, 28))
        self.btn_sumar.setObjectName("btn_sumar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 386, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Numero 1:"))
        self.label_2.setText(_translate("MainWindow", "Numero 2:"))
        self.btn_sumar.setText(_translate("MainWindow", "SUMA"))
